export { default as Navbar } from './Navbar';
export { default as Movie } from './Movie';
export { default as MovieList } from './MovieList';
export { default as MovieDeatils } from './MovieDeatils';
export { default as CategoryGenre } from './CategoryGenre';
export { default as Search } from './Search';
export { default as Actors } from './Actors';
export { default as LoginLogout } from './LoginLogout';
export { default as Rating } from './Rating';
export { default as Cast } from './Cast';
export { default as Casts } from './Casts';
export { default as Trailer } from './Trailer';
export { default as ActorsMovies } from './ActorsMovies';
export { default as Favorites } from './Favorites';
export { default as WatchLists } from './WatchList';

export { default as Error } from './Error';
export { default as Loading } from './Loading';
export { default as NotFound } from './NotFound';
